My submission for the weekly challenge
dscrait/weekly-challenges pull request #10
Opened 2020-09-08 15:03 UTC by hdck007

I have created two scripts that change your wallpaper on ubuntu and termux(for android).

2020-10-08 21:20 UTC, meta-boy commented on README.md
> +<<<<<<< HEAD
Remove merge conflicts

2020-10-08 21:20 UTC, meta-boy requested changes
Remove merge conflicts

2020-10-09 03:16 UTC, hdck007 commented
I have added new commits to solve the merge conflicts.

2020-10-09 09:43 UTC, meta-boy approved these changes
LGTM

2020-10-09 09:44 UTC, merged